### ISSUE TITLE
非常有用的模块，建议提交至lsposed仓库

### ISSUE THREAD

**Issue by Marukon** [chenyue404/IntentFilter#1]
这个模块能够解决从浏览器访问网页时总是跳转到app的问题，非常好用。谢谢作者！
建议作者提交至lsposed仓库（https://github.com/Xposed-Modules-Repo/submission ）， 方便更多人发现这么好用的模块。

**Comment by chenyue404** [comment]
没打算提交。本来是自用的，放出来是方便需要的人使用，不用重复造轮子。提交仓库，可预见的会有很多需求提过来，这些又不一定是我想要的，处理起来就很麻烦。而且会有一些小白用户搞不清楚怎么用，解释起来很麻烦。

**Comment by Marukon** [comment]
谢谢作者的回复。这个真是一个非常好用的模块，再次谢谢作者的付出。
